name: autocg_ml
channels:
  - conda-forge
dependencies:
  - python=3.9
  - rdkit
  - numpy<2
  - pandas
  - scipy
  - scikit-learn
  - joblib
  - networkx
  - matplotlib
  - lightgbm
  - seaborn
  - pytorch
  - pip
  - pip:
    - opencv-python
    - torch-geometric
