import argparse
import numpy as np
import sys
from typing import List, Dict, Tuple

class Atom:

    def __init__(self, resnum, resname, atomname, atomnum, x, y, z, vx=0.0, vy=0.0, vz=0.0):
        self.resnum = resnum
        self.resname = resname
        self.atomname = atomname
        self.atomnum = atomnum
        self.x = x
        self.y = y
        self.z = z
        self.vx = vx
        self.vy = vy
        self.vz = vz

class GROFile:

    @staticmethod
    def read(filename):
        atoms = []
        box = None
        with open(filename, 'r') as f:
            lines = f.readlines()
        title = lines[0].strip()
        natoms = int(lines[1].strip())
        for i in range(2, 2 + natoms):
            line = lines[i]
            resnum = int(line[0:5].strip())
            resname = line[5:10].strip()
            atomname = line[10:15].strip()
            atomnum = int(line[15:20].strip())
            x = float(line[20:28].strip())
            y = float(line[28:36].strip())
            z = float(line[36:44].strip())
            vx, vy, vz = (0.0, 0.0, 0.0)
            if len(line) > 44:
                try:
                    vx = float(line[44:52].strip())
                    vy = float(line[52:60].strip())
                    vz = float(line[60:68].strip())
                except:
                    pass
            atoms.append(Atom(resnum, resname, atomname, atomnum, x, y, z, vx, vy, vz))
        box_line = lines[2 + natoms].strip().split()
        box = [float(x) for x in box_line]
        return (atoms, box, title)

    @staticmethod
    def write(filename, atoms, box, title='Backmapped structure'):
        with open(filename, 'w') as f:
            f.write(f'{title}\n')
            f.write(f'{len(atoms)}\n')
            for atom in atoms:
                f.write(f'{atom.resnum % 100000:5d}{atom.resname:5s}{atom.atomname:>5s}{atom.atomnum % 100000:5d}{atom.x:8.3f}{atom.y:8.3f}{atom.z:8.3f}{atom.vx:8.4f}{atom.vy:8.4f}{atom.vz:8.4f}\n')
            if len(box) == 3:
                f.write(f'{box[0]:10.5f}{box[1]:10.5f}{box[2]:10.5f}\n')
            elif len(box) == 9:
                f.write(f'{box[0]:10.5f}{box[1]:10.5f}{box[2]:10.5f}{box[3]:10.5f}{box[4]:10.5f}{box[5]:10.5f}{box[6]:10.5f}{box[7]:10.5f}{box[8]:10.5f}\n')

class PDBFile:

    @staticmethod
    def write(filename, atoms, box):
        with open(filename, 'w') as f:
            f.write('TITLE     Backmapped structure\n')
            f.write('REMARK    Generated by backmapper.py\n')
            for i, atom in enumerate(atoms):
                x_ang = atom.x * 10.0
                y_ang = atom.y * 10.0
                z_ang = atom.z * 10.0
                f.write(f'ATOM  {atom.atomnum % 100000:5d} {atom.atomname:4s} {atom.resname:3s} A{atom.resnum % 10000:4d}    {x_ang:8.3f}{y_ang:8.3f}{z_ang:8.3f}  1.00  0.00           {atom.atomname[0]:>2s}\n')
            if len(box) >= 3:
                a = box[0] * 10.0
                b = box[1] * 10.0
                c = box[2] * 10.0
                f.write(f'CRYST1{a:9.3f}{b:9.3f}{c:9.3f}  90.00  90.00  90.00 P 1           1\n')
            f.write('END\n')

class MappingFile:

    @staticmethod
    def read(filename):
        mapping = {}
        with open(filename, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                parts = line.split()
                if len(parts) >= 2:
                    cg_idx = int(parts[0])
                    aa_indices = [int(x) for x in parts[1:]]
                    for aa_idx in aa_indices:
                        if cg_idx not in mapping:
                            mapping[cg_idx] = []
                        mapping[cg_idx].append(aa_idx)
        return mapping

class BackMapper:

    def __init__(self, radius=0.15):
        self.radius = radius

    def random_position_in_sphere(self, center, radius):
        while True:
            x = np.random.uniform(-radius, radius)
            y = np.random.uniform(-radius, radius)
            z = np.random.uniform(-radius, radius)
            if x * x + y * y + z * z <= radius * radius:
                return (center[0] + x, center[1] + y, center[2] + z)

    def backmap(self, cg_atoms, aa_template_atoms, mapping, num_molecules):
        aa_atoms = []
        atoms_per_molecule = len(aa_template_atoms)
        for mol_idx in range(num_molecules):
            for aa_local_idx in range(atoms_per_molecule):
                cg_local_idx = None
                for cg_idx, aa_list in mapping.items():
                    if aa_local_idx in aa_list:
                        cg_local_idx = cg_idx
                        break
                if cg_local_idx is None:
                    continue
                cg_global_idx = mol_idx * len(set(mapping.keys())) + cg_local_idx
                if cg_global_idx >= len(cg_atoms):
                    continue
                cg_atom = cg_atoms[cg_global_idx]
                cg_pos = np.array([cg_atom.x, cg_atom.y, cg_atom.z])
                template_atom = aa_template_atoms[aa_local_idx]
                new_pos = self.random_position_in_sphere(cg_pos, self.radius)
                new_atom = Atom(resnum=mol_idx + 1, resname=template_atom.resname, atomname=template_atom.atomname, atomnum=len(aa_atoms) + 1, x=new_pos[0], y=new_pos[1], z=new_pos[2], vx=0.0, vy=0.0, vz=0.0)
                aa_atoms.append(new_atom)
        return aa_atoms

def main():
    parser = argparse.ArgumentParser(description='粗粒化结构向全原子结构的反向映射工具', formatter_class=argparse.RawDescriptionHelpFormatter, epilog='\nExample usage:\n  python backmapper.py -f box_cg.gro -gro PU1.gro PU2.gro -num 2 3 -m PU1.map PU2.map -d 0.15 -o backmap\n        ')
    parser.add_argument('-f', '--input', required=True, help='Input coarse-grained GRO file')
    parser.add_argument('-gro', '--templates', nargs='+', required=True, help='List of all-atom template GRO files')
    parser.add_argument('-num', '--numbers', nargs='+', type=int, required=True, help='Number of molecules for each species')
    parser.add_argument('-m', '--maps', nargs='+', required=True, help='List of mapping files')
    parser.add_argument('-d', '--distance', type=float, default=0.15, help='Random placement radius (nm), default: 0.15')
    parser.add_argument('-o', '--output', default='backmap', help='Output file prefix, default: backmap')
    args = parser.parse_args()
    if not len(args.templates) == len(args.numbers) == len(args.maps):
        sys.exit(1)
    cg_atoms, box, cg_title = GROFile.read(args.input)
    backmapper = BackMapper(radius=args.distance)
    all_aa_atoms = []
    for i, (template_file, num_mol, map_file) in enumerate(zip(args.templates, args.numbers, args.maps)):
        aa_template_atoms, _, _ = GROFile.read(template_file)
        mapping = MappingFile.read(map_file)
        aa_atoms = backmapper.backmap(cg_atoms, aa_template_atoms, mapping, num_mol)
        all_aa_atoms.extend(aa_atoms)
    for i, atom in enumerate(all_aa_atoms):
        atom.atomnum = i + 1
    output_gro = f'{args.output}.gro'
    GROFile.write(output_gro, all_aa_atoms, box, 'Backmapped structure')
    output_pdb = f'{args.output}.pdb'
    PDBFile.write(output_pdb, all_aa_atoms, box)
if __name__ == '__main__':
    main()
